---
- name: install desktop packages
  pacman:
    name:
      - xorg
      - xterm 
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
      - polybar
      - rofi
      - autorandr
      - arandr              # visual frontend for XRandR
      - arc-gtk-theme
      - lxappearance          # theme manager
      - flameshot           # screenshots
      - brightnessctl # brightness manager
      - dmenu
      - dunst
      - nitrogen
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
      - vulkan-radeon
      - libva-utils
      - xf86-video-amdgpu
    state: present

- name: install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pavucontrol
      - pamixer
      - alsa-utils
      - audacity
    state: present

- name: install applications packages
  pacman:
    name:
      - imv                   # img visualizer
      # - wezterm               # terminal emulator
      - evince                # pdf viewer
      # - evolution             # mail 
      - thunderbird           # mail & rss client
      - gnome-keyring         # evolution gnome keyring
      - seahorse              # keyring manager
      - firefox
      - flatpak               # package manager
      - gimp                  # img editor
      - kolourpaint           # img editor
      - shotwell              # photo manager
      - libreoffice-fresh     # libreoffice suite
      - barrier
      - bleachbit
      - blender
      - blueman
      - calc
      - darktable
      - discord
      - filezilla
      - gthumb
      - gzip
      - inkscape
      - kate
      - obs-studio
      - rxvt-unicode
      - spice
      - spice-vdagent
      - tailscale
      - tmux
      - veracrypt
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-guest-utils
      - virtualbox-host-dkms
      - wget
      - wireguard-tools
      - xcape
      - yubico-pam
      - yubikey-personalization-gui
      - yubioath-desktop
      - wacomtablet
      - xf86-input-wacom
      - mpv                   # video player
      - vlc                   # video player
      - pcmanfm               # file manager
      - tumbler               # thumbnailer
      - rdesktop              # remote desktop client
      - remmina               # remote desktop client
      - freerdp               # remmina dep for rdp
      - transmission-gtk      # torrent downloader
      - variety               # random backgrounds
      - papirus-icon-theme    # icon theme
      - gnome-themes-extra    # gtk themes
      - yt-dlp                # youtube dowload utility
      - gopass                # password manager
      - keepassxc             # password manager
      - okular                # pdf editor, no image overlay
      - xournalpp             # pdf editor, no form
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv --keyserver keyserver.ubuntu.com '{{item}}'
  loop:
    # - F4B432D5D67990E3 # wob
    - 1A09227B1F435A33 # otb-unifont

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - brave-beta-bin        # web browser
      - mqtt-explorer-appimage
      - oh-my-zsh-git
      - otb-unifont
      - tabby-bin
      - tabby-bin-debug
      - zenmap
      - camunda-modeler-bin
      - drawio-desktop-bin
      - pycharm-professional
      - realvnc-vnc-viewer
      - remmina-plugin-folder
      - remmina-plugin-rdesktop
      - wacom-settings-git
      - wacom-utility
      - adb-sync-git # android dir sync
      - downgrade # package downgrader
      - lf # cli file manager
      - otf-font-awesome
      - pastel # color viewer
      - rbenv # ruby env manager
      - iwgtk # gui for iwd

# - name: test swaylock-fancy
#   stat:
#     path: /bin/swaylock-fancy
#   register: swaylock

# - name: clone swaylock-fancy
#   git:
#     repo: https://github.com/eoli3n/swaylock-fancy
#     dest: /tmp/swaylock-fancy
#   when: not swaylock.stat.exists

# - name: install swaylock-fancy
#   shell: make install
#   args:
#     chdir: /tmp/swaylock-fancy
#   when: not swaylock.stat.exists
